// Code generated by protoc-gen-go.
// source: battery.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Battery struct {
	// / \brief Name of the battery
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// / \brief Real voltage in volts.
	Voltage          *float64 `protobuf:"fixed64,2,req,name=voltage" json:"voltage,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Battery) Reset()                    { *m = Battery{} }
func (m *Battery) String() string            { return proto.CompactTextString(m) }
func (*Battery) ProtoMessage()               {}
func (*Battery) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Battery) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Battery) GetVoltage() float64 {
	if m != nil && m.Voltage != nil {
		return *m.Voltage
	}
	return 0
}

func init() {
	proto.RegisterType((*Battery)(nil), "gazebo.msgs.Battery")
}

func init() { proto.RegisterFile("battery.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0x2c, 0x29,
	0x49, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d,
	0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0xd2, 0xe0, 0x62, 0x77, 0x82, 0xc8, 0x0a, 0xf1, 0x70,
	0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0x70, 0x0a, 0xf1, 0x73, 0xb1, 0x97,
	0xe5, 0xe7, 0x94, 0x24, 0xa6, 0xa7, 0x4a, 0x30, 0x01, 0x05, 0x18, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xa6, 0x1c, 0xab, 0xbd, 0x46, 0x00, 0x00, 0x00,
}
