// Code generated by protoc-gen-go.
// source: density.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Density struct {
	Density          *float64 `protobuf:"fixed64,1,req,name=density" json:"density,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Density) Reset()                    { *m = Density{} }
func (m *Density) String() string            { return proto.CompactTextString(m) }
func (*Density) ProtoMessage()               {}
func (*Density) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{0} }

func (m *Density) GetDensity() float64 {
	if m != nil && m.Density != nil {
		return *m.Density
	}
	return 0
}

func init() {
	proto.RegisterType((*Density)(nil), "gazebo.msgs.Density")
}

func init() { proto.RegisterFile("density.proto", fileDescriptor16) }

var fileDescriptor16 = []byte{
	// 71 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x49, 0xcd, 0x2b,
	0xce, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d,
	0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x92, 0xe2, 0x62, 0x77, 0x81, 0xc8, 0x0a, 0xf1, 0x73,
	0xb1, 0x43, 0x15, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0x30, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xec, 0xc3, 0xed, 0x38, 0x00, 0x00, 0x00,
}
