// Code generated by protoc-gen-go.
// source: distortion.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Distortion struct {
	Center           *Vector2D `protobuf:"bytes,1,opt,name=center" json:"center,omitempty"`
	K1               *float64  `protobuf:"fixed64,2,opt,name=k1" json:"k1,omitempty"`
	K2               *float64  `protobuf:"fixed64,3,opt,name=k2" json:"k2,omitempty"`
	K3               *float64  `protobuf:"fixed64,4,opt,name=k3" json:"k3,omitempty"`
	P1               *float64  `protobuf:"fixed64,5,opt,name=p1" json:"p1,omitempty"`
	P2               *float64  `protobuf:"fixed64,6,opt,name=p2" json:"p2,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Distortion) Reset()                    { *m = Distortion{} }
func (m *Distortion) String() string            { return proto.CompactTextString(m) }
func (*Distortion) ProtoMessage()               {}
func (*Distortion) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{0} }

func (m *Distortion) GetCenter() *Vector2D {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *Distortion) GetK1() float64 {
	if m != nil && m.K1 != nil {
		return *m.K1
	}
	return 0
}

func (m *Distortion) GetK2() float64 {
	if m != nil && m.K2 != nil {
		return *m.K2
	}
	return 0
}

func (m *Distortion) GetK3() float64 {
	if m != nil && m.K3 != nil {
		return *m.K3
	}
	return 0
}

func (m *Distortion) GetP1() float64 {
	if m != nil && m.P1 != nil {
		return *m.P1
	}
	return 0
}

func (m *Distortion) GetP2() float64 {
	if m != nil && m.P2 != nil {
		return *m.P2
	}
	return 0
}

func init() {
	proto.RegisterType((*Distortion)(nil), "gazebo.msgs.Distortion")
}

func init() { proto.RegisterFile("distortion.proto", fileDescriptor18) }

var fileDescriptor18 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xc9, 0x2c, 0x2e,
	0xc9, 0x2f, 0x2a, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f,
	0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x96, 0xe2, 0x2b, 0x4b, 0x4d, 0x06, 0x4a,
	0x1b, 0xa5, 0x40, 0x24, 0x95, 0xf2, 0xb9, 0xb8, 0x5c, 0xe0, 0x1a, 0x84, 0x54, 0xb9, 0xd8, 0x92,
	0x53, 0xf3, 0x4a, 0x52, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0x90, 0xf4,
	0xea, 0x85, 0x41, 0xb5, 0x0a, 0x71, 0x71, 0x31, 0x65, 0x1b, 0x4a, 0x30, 0x01, 0x95, 0x30, 0x82,
	0xd9, 0x46, 0x12, 0xcc, 0x70, 0xb6, 0xb1, 0x04, 0x0b, 0x8c, 0x5d, 0x60, 0x28, 0xc1, 0x0a, 0x67,
	0x1b, 0x49, 0xb0, 0x81, 0xd8, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x5b, 0x48, 0xbf, 0xa0,
	0x00, 0x00, 0x00,
}
