// Code generated by protoc-gen-go.
// source: factory.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Factory struct {
	// / \brief SDF description in string format.
	Sdf *string `protobuf:"bytes,1,opt,name=sdf" json:"sdf,omitempty"`
	// / \brief Full path to SDF file.
	SdfFilename *string `protobuf:"bytes,2,opt,name=sdf_filename" json:"sdf_filename,omitempty"`
	// / \brief Pose where the entity will be spawned.
	Pose *Pose `protobuf:"bytes,3,opt,name=pose" json:"pose,omitempty"`
	// / \brief Name of the entity which will be updated.
	EditName *string `protobuf:"bytes,4,opt,name=edit_name" json:"edit_name,omitempty"`
	// / \brief Name of model to clone.
	CloneModelName *string `protobuf:"bytes,5,opt,name=clone_model_name" json:"clone_model_name,omitempty"`
	// / \brief Whether the server is allowed to rename the model in case of
	// / overlap with existing models.
	AllowRenaming    *bool  `protobuf:"varint,6,opt,name=allow_renaming,def=1" json:"allow_renaming,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Factory) Reset()                    { *m = Factory{} }
func (m *Factory) String() string            { return proto.CompactTextString(m) }
func (*Factory) ProtoMessage()               {}
func (*Factory) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{0} }

const Default_Factory_AllowRenaming bool = true

func (m *Factory) GetSdf() string {
	if m != nil && m.Sdf != nil {
		return *m.Sdf
	}
	return ""
}

func (m *Factory) GetSdfFilename() string {
	if m != nil && m.SdfFilename != nil {
		return *m.SdfFilename
	}
	return ""
}

func (m *Factory) GetPose() *Pose {
	if m != nil {
		return m.Pose
	}
	return nil
}

func (m *Factory) GetEditName() string {
	if m != nil && m.EditName != nil {
		return *m.EditName
	}
	return ""
}

func (m *Factory) GetCloneModelName() string {
	if m != nil && m.CloneModelName != nil {
		return *m.CloneModelName
	}
	return ""
}

func (m *Factory) GetAllowRenaming() bool {
	if m != nil && m.AllowRenaming != nil {
		return *m.AllowRenaming
	}
	return Default_Factory_AllowRenaming
}

func init() {
	proto.RegisterType((*Factory)(nil), "gazebo.msgs.Factory")
}

func init() { proto.RegisterFile("factory.proto", fileDescriptor20) }

var fileDescriptor20 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4b, 0x4c, 0x2e,
	0xc9, 0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d,
	0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x96, 0xe2, 0x2a, 0xc8, 0x2f, 0x4e, 0x85, 0x48, 0x28, 0xcd,
	0x60, 0xe4, 0x62, 0x77, 0x83, 0x28, 0x15, 0xe2, 0xe6, 0x62, 0x2e, 0x4e, 0x49, 0x93, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x14, 0x12, 0xe1, 0xe2, 0x01, 0x72, 0xe2, 0xd3, 0x32, 0x73, 0x52, 0xf3, 0x12,
	0x73, 0x53, 0x25, 0x98, 0xc0, 0xa2, 0xf2, 0x5c, 0x2c, 0x20, 0xcd, 0x12, 0xcc, 0x40, 0x1e, 0xb7,
	0x91, 0xa0, 0x1e, 0x92, 0xb1, 0x7a, 0x01, 0x40, 0x09, 0x21, 0x41, 0x2e, 0xce, 0xd4, 0x94, 0xcc,
	0x92, 0x78, 0xb0, 0x1e, 0x16, 0xb0, 0x1e, 0x09, 0x2e, 0x81, 0xe4, 0x9c, 0xfc, 0xbc, 0xd4, 0xf8,
	0xdc, 0xfc, 0x94, 0xd4, 0x1c, 0x88, 0x0c, 0x2b, 0x58, 0x46, 0x86, 0x8b, 0x2f, 0x31, 0x27, 0x27,
	0xbf, 0x3c, 0xbe, 0x08, 0x64, 0x47, 0x66, 0x5e, 0xba, 0x04, 0x1b, 0x50, 0x9c, 0xc3, 0x8a, 0xa5,
	0xa4, 0xa8, 0x34, 0x15, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xf2, 0x5f, 0x49, 0xc3, 0x00, 0x00,
	0x00,
}
