// Code generated by protoc-gen-go.
// source: fog.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Fog_FogType int32

const (
	Fog_NONE         Fog_FogType = 1
	Fog_LINEAR       Fog_FogType = 2
	Fog_EXPONENTIAL  Fog_FogType = 3
	Fog_EXPONENTIAL2 Fog_FogType = 4
)

var Fog_FogType_name = map[int32]string{
	1: "NONE",
	2: "LINEAR",
	3: "EXPONENTIAL",
	4: "EXPONENTIAL2",
}
var Fog_FogType_value = map[string]int32{
	"NONE":         1,
	"LINEAR":       2,
	"EXPONENTIAL":  3,
	"EXPONENTIAL2": 4,
}

func (x Fog_FogType) Enum() *Fog_FogType {
	p := new(Fog_FogType)
	*p = x
	return p
}
func (x Fog_FogType) String() string {
	return proto.EnumName(Fog_FogType_name, int32(x))
}
func (x *Fog_FogType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Fog_FogType_value, data, "Fog_FogType")
	if err != nil {
		return err
	}
	*x = Fog_FogType(value)
	return nil
}
func (Fog_FogType) EnumDescriptor() ([]byte, []int) { return fileDescriptor22, []int{0, 0} }

type Fog struct {
	Type             *Fog_FogType `protobuf:"varint,1,opt,name=type,enum=gazebo.msgs.Fog_FogType" json:"type,omitempty"`
	Color            *Color       `protobuf:"bytes,2,opt,name=color" json:"color,omitempty"`
	Density          *float32     `protobuf:"fixed32,3,opt,name=density" json:"density,omitempty"`
	Start            *float32     `protobuf:"fixed32,4,opt,name=start" json:"start,omitempty"`
	End              *float32     `protobuf:"fixed32,5,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Fog) Reset()                    { *m = Fog{} }
func (m *Fog) String() string            { return proto.CompactTextString(m) }
func (*Fog) ProtoMessage()               {}
func (*Fog) Descriptor() ([]byte, []int) { return fileDescriptor22, []int{0} }

func (m *Fog) GetType() Fog_FogType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Fog_NONE
}

func (m *Fog) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *Fog) GetDensity() float32 {
	if m != nil && m.Density != nil {
		return *m.Density
	}
	return 0
}

func (m *Fog) GetStart() float32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *Fog) GetEnd() float32 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*Fog)(nil), "gazebo.msgs.Fog")
	proto.RegisterEnum("gazebo.msgs.Fog_FogType", Fog_FogType_name, Fog_FogType_value)
}

func init() { proto.RegisterFile("fog.proto", fileDescriptor22) }

var fileDescriptor22 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xcb, 0x4f, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d,
	0x4e, 0x2f, 0x96, 0xe2, 0x4e, 0xce, 0xcf, 0xc9, 0x2f, 0x82, 0xc8, 0x28, 0x1d, 0x64, 0xe4, 0x62,
	0x76, 0xcb, 0x4f, 0x17, 0x52, 0xe3, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x33, 0x92, 0xd0, 0x43, 0xd2, 0xa0, 0x07, 0x94, 0x07, 0xe1, 0x10, 0xa0, 0xbc, 0x90, 0x22,
	0x17, 0x2b, 0x58, 0xbb, 0x04, 0x13, 0x50, 0x21, 0xb7, 0x91, 0x10, 0x8a, 0x42, 0x67, 0x90, 0x8c,
	0x10, 0x3f, 0x17, 0x7b, 0x4a, 0x6a, 0x5e, 0x71, 0x66, 0x49, 0xa5, 0x04, 0x33, 0x50, 0x11, 0x93,
	0x10, 0x2f, 0x17, 0x6b, 0x71, 0x49, 0x62, 0x51, 0x89, 0x04, 0x0b, 0x98, 0xcb, 0xcd, 0xc5, 0x9c,
	0x9a, 0x97, 0x22, 0xc1, 0x0a, 0xe2, 0x28, 0x39, 0x71, 0xb1, 0xc3, 0x8c, 0xe6, 0xe0, 0x62, 0xf1,
	0xf3, 0xf7, 0x73, 0x15, 0x60, 0x14, 0xe2, 0xe2, 0x62, 0xf3, 0xf1, 0xf4, 0x73, 0x75, 0x0c, 0x12,
	0x60, 0x02, 0x9a, 0xc6, 0xed, 0x1a, 0x11, 0x00, 0x14, 0xf7, 0x0b, 0xf1, 0x74, 0xf4, 0x11, 0x60,
	0x16, 0x12, 0xe0, 0xe2, 0x41, 0x12, 0x30, 0x12, 0x60, 0x01, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb3,
	0xb0, 0xf4, 0xba, 0xe9, 0x00, 0x00, 0x00,
}
