// Code generated by protoc-gen-go.
// source: gz_string.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GzString struct {
	Data             *string `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GzString) Reset()                    { *m = GzString{} }
func (m *GzString) String() string            { return proto.CompactTextString(m) }
func (*GzString) ProtoMessage()               {}
func (*GzString) Descriptor() ([]byte, []int) { return fileDescriptor29, []int{0} }

func (m *GzString) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GzString)(nil), "gazebo.msgs.GzString")
}

func init() { proto.RegisterFile("gz_string.proto", fileDescriptor29) }

var fileDescriptor29 = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xaf, 0x8a, 0x2f,
	0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac,
	0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x92, 0xe0, 0xe2, 0x70, 0xaf, 0x0a, 0x06,
	0x4b, 0x0b, 0xf1, 0x70, 0xb1, 0xa4, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0x70, 0x02,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x47, 0x60, 0x5e, 0x38, 0x00, 0x00, 0x00,
}
