// Code generated by protoc-gen-go.
// source: heightmapgeom.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HeightmapGeom struct {
	Image            *Image                   `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	Size             *Vector3D                `protobuf:"bytes,2,req,name=size" json:"size,omitempty"`
	Origin           *Vector3D                `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	Heights          []float32                `protobuf:"fixed32,4,rep,name=heights" json:"heights,omitempty"`
	Width            *int32                   `protobuf:"varint,5,opt,name=width" json:"width,omitempty"`
	Height           *int32                   `protobuf:"varint,6,opt,name=height" json:"height,omitempty"`
	Texture          []*HeightmapGeom_Texture `protobuf:"bytes,7,rep,name=texture" json:"texture,omitempty"`
	Blend            []*HeightmapGeom_Blend   `protobuf:"bytes,8,rep,name=blend" json:"blend,omitempty"`
	UseTerrainPaging *bool                    `protobuf:"varint,9,opt,name=use_terrain_paging" json:"use_terrain_paging,omitempty"`
	// The image filename
	Filename         *string `protobuf:"bytes,10,opt,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeightmapGeom) Reset()                    { *m = HeightmapGeom{} }
func (m *HeightmapGeom) String() string            { return proto.CompactTextString(m) }
func (*HeightmapGeom) ProtoMessage()               {}
func (*HeightmapGeom) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{0} }

func (m *HeightmapGeom) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *HeightmapGeom) GetSize() *Vector3D {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *HeightmapGeom) GetOrigin() *Vector3D {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *HeightmapGeom) GetHeights() []float32 {
	if m != nil {
		return m.Heights
	}
	return nil
}

func (m *HeightmapGeom) GetWidth() int32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *HeightmapGeom) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *HeightmapGeom) GetTexture() []*HeightmapGeom_Texture {
	if m != nil {
		return m.Texture
	}
	return nil
}

func (m *HeightmapGeom) GetBlend() []*HeightmapGeom_Blend {
	if m != nil {
		return m.Blend
	}
	return nil
}

func (m *HeightmapGeom) GetUseTerrainPaging() bool {
	if m != nil && m.UseTerrainPaging != nil {
		return *m.UseTerrainPaging
	}
	return false
}

func (m *HeightmapGeom) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

type HeightmapGeom_Texture struct {
	Diffuse          *string  `protobuf:"bytes,1,req,name=diffuse" json:"diffuse,omitempty"`
	Normal           *string  `protobuf:"bytes,2,req,name=normal" json:"normal,omitempty"`
	Size             *float64 `protobuf:"fixed64,3,req,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HeightmapGeom_Texture) Reset()                    { *m = HeightmapGeom_Texture{} }
func (m *HeightmapGeom_Texture) String() string            { return proto.CompactTextString(m) }
func (*HeightmapGeom_Texture) ProtoMessage()               {}
func (*HeightmapGeom_Texture) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{0, 0} }

func (m *HeightmapGeom_Texture) GetDiffuse() string {
	if m != nil && m.Diffuse != nil {
		return *m.Diffuse
	}
	return ""
}

func (m *HeightmapGeom_Texture) GetNormal() string {
	if m != nil && m.Normal != nil {
		return *m.Normal
	}
	return ""
}

func (m *HeightmapGeom_Texture) GetSize() float64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type HeightmapGeom_Blend struct {
	MinHeight        *float64 `protobuf:"fixed64,1,req,name=min_height" json:"min_height,omitempty"`
	FadeDist         *float64 `protobuf:"fixed64,2,req,name=fade_dist" json:"fade_dist,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HeightmapGeom_Blend) Reset()                    { *m = HeightmapGeom_Blend{} }
func (m *HeightmapGeom_Blend) String() string            { return proto.CompactTextString(m) }
func (*HeightmapGeom_Blend) ProtoMessage()               {}
func (*HeightmapGeom_Blend) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{0, 1} }

func (m *HeightmapGeom_Blend) GetMinHeight() float64 {
	if m != nil && m.MinHeight != nil {
		return *m.MinHeight
	}
	return 0
}

func (m *HeightmapGeom_Blend) GetFadeDist() float64 {
	if m != nil && m.FadeDist != nil {
		return *m.FadeDist
	}
	return 0
}

func init() {
	proto.RegisterType((*HeightmapGeom)(nil), "gazebo.msgs.HeightmapGeom")
	proto.RegisterType((*HeightmapGeom_Texture)(nil), "gazebo.msgs.HeightmapGeom.Texture")
	proto.RegisterType((*HeightmapGeom_Blend)(nil), "gazebo.msgs.HeightmapGeom.Blend")
}

func init() { proto.RegisterFile("heightmapgeom.proto", fileDescriptor32) }

var fileDescriptor32 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0xd3, 0x96, 0x52, 0x3a, 0x15, 0xd4, 0x31, 0x26, 0x9b, 0x9e, 0x2a, 0xc6, 0x84, 0x53,
	0x4d, 0xe0, 0xe2, 0xd9, 0x8b, 0x7a, 0x37, 0x5e, 0xc9, 0x62, 0xa7, 0x65, 0x13, 0xb6, 0x4b, 0xb6,
	0x8b, 0x1a, 0x7e, 0x93, 0x3f, 0xd2, 0x69, 0x0b, 0x89, 0x1c, 0xf4, 0x38, 0x3b, 0xef, 0x7b, 0xb3,
	0xef, 0xc1, 0xd5, 0x9a, 0x54, 0xb5, 0x76, 0x5a, 0x6e, 0x2b, 0x32, 0x3a, 0xdf, 0x5a, 0xe3, 0x0c,
	0x26, 0x95, 0xdc, 0xd3, 0xca, 0xe4, 0xba, 0xa9, 0x9a, 0x34, 0x51, 0x5a, 0x56, 0xd4, 0x6f, 0xd2,
	0xc9, 0x07, 0xbd, 0x3b, 0x63, 0x17, 0x45, 0x3f, 0x4f, 0xbf, 0x03, 0x18, 0x3f, 0x1f, 0x1d, 0x9e,
	0xd8, 0x01, 0x6f, 0x20, 0xec, 0x00, 0xe1, 0x65, 0xde, 0x2c, 0x99, 0x63, 0xfe, 0xcb, 0x2b, 0x7f,
	0x69, 0x37, 0x78, 0x0b, 0x83, 0x46, 0xed, 0x49, 0xf8, 0x99, 0xcf, 0x8a, 0xeb, 0x13, 0xc5, 0xdb,
	0xc1, 0x1f, 0xef, 0x60, 0x68, 0xac, 0xaa, 0x54, 0x2d, 0x82, 0xce, 0xe8, 0x0f, 0xd9, 0x39, 0x44,
	0x7d, 0x82, 0x46, 0x0c, 0xb2, 0x60, 0xe6, 0xe3, 0x18, 0xc2, 0x4f, 0x55, 0xb8, 0xb5, 0x08, 0x19,
	0x0b, 0x71, 0x02, 0xc3, 0x7e, 0x2f, 0x86, 0xdd, 0xbc, 0x80, 0xc8, 0xd1, 0x97, 0xdb, 0x59, 0x12,
	0x11, 0xeb, 0x93, 0xf9, 0xf4, 0xc4, 0xf7, 0x24, 0x4b, 0xfe, 0xda, 0x2b, 0xf1, 0x1e, 0xc2, 0xd5,
	0x86, 0xea, 0x42, 0x8c, 0x3a, 0x24, 0xfb, 0x07, 0x79, 0x6c, 0x75, 0x98, 0x02, 0xee, 0x1a, 0x5a,
	0x3a, 0xb2, 0x56, 0xaa, 0x7a, 0xb9, 0x95, 0x9c, 0xa3, 0x12, 0x31, 0xff, 0x60, 0x84, 0x17, 0x30,
	0x2a, 0x15, 0xab, 0xa4, 0x26, 0x01, 0xfc, 0x12, 0xa7, 0x0f, 0x10, 0x1d, 0x2f, 0x71, 0x9c, 0x42,
	0x95, 0x25, 0xc3, 0xdc, 0x9f, 0x3f, 0x8b, 0xdb, 0xff, 0xd7, 0xc6, 0x6a, 0xb9, 0xe9, 0xda, 0x8a,
	0xf1, 0xec, 0xd0, 0x5d, 0xc0, 0x93, 0x97, 0xe6, 0x10, 0xf6, 0x07, 0x11, 0x40, 0xf3, 0xa1, 0x43,
	0xd4, 0x16, 0xf5, 0xf0, 0x12, 0xe2, 0x52, 0x16, 0xb4, 0x2c, 0x54, 0xe3, 0x3a, 0xda, 0xfb, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x00, 0x1a, 0x8e, 0x23, 0xee, 0x01, 0x00, 0x00,
}
