// Code generated by protoc-gen-go.
// source: int.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Int struct {
	// / Integer data
	Data             *int32 `protobuf:"varint,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Int) Reset()                    { *m = Int{} }
func (m *Int) String() string            { return proto.CompactTextString(m) }
func (*Int) ProtoMessage()               {}
func (*Int) Descriptor() ([]byte, []int) { return fileDescriptor41, []int{0} }

func (m *Int) GetData() int32 {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return 0
}

func init() {
	proto.RegisterType((*Int)(nil), "gazebo.msgs.Int")
}

func init() { proto.RegisterFile("int.proto", fileDescriptor41) }

var fileDescriptor41 = []byte{
	// 69 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xcc, 0x2b, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d,
	0x4e, 0x2f, 0x56, 0x12, 0xe6, 0x62, 0xf6, 0xcc, 0x2b, 0x11, 0xe2, 0xe1, 0x62, 0x49, 0x49, 0x2c,
	0x49, 0x94, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x05, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xdd, 0x3f,
	0xcd, 0x2d, 0x00, 0x00, 0x00,
}
