// Code generated by protoc-gen-go.
// source: joint_wrench.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type JointWrench struct {
	Body_1Name       *string `protobuf:"bytes,1,req,name=body_1_name" json:"body_1_name,omitempty"`
	Body_1Id         *uint32 `protobuf:"varint,2,req,name=body_1_id" json:"body_1_id,omitempty"`
	Body_2Name       *string `protobuf:"bytes,3,req,name=body_2_name" json:"body_2_name,omitempty"`
	Body_2Id         *uint32 `protobuf:"varint,4,req,name=body_2_id" json:"body_2_id,omitempty"`
	Body_1Wrench     *Wrench `protobuf:"bytes,5,req,name=body_1_wrench" json:"body_1_wrench,omitempty"`
	Body_2Wrench     *Wrench `protobuf:"bytes,6,req,name=body_2_wrench" json:"body_2_wrench,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JointWrench) Reset()                    { *m = JointWrench{} }
func (m *JointWrench) String() string            { return proto.CompactTextString(m) }
func (*JointWrench) ProtoMessage()               {}
func (*JointWrench) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{0} }

func (m *JointWrench) GetBody_1Name() string {
	if m != nil && m.Body_1Name != nil {
		return *m.Body_1Name
	}
	return ""
}

func (m *JointWrench) GetBody_1Id() uint32 {
	if m != nil && m.Body_1Id != nil {
		return *m.Body_1Id
	}
	return 0
}

func (m *JointWrench) GetBody_2Name() string {
	if m != nil && m.Body_2Name != nil {
		return *m.Body_2Name
	}
	return ""
}

func (m *JointWrench) GetBody_2Id() uint32 {
	if m != nil && m.Body_2Id != nil {
		return *m.Body_2Id
	}
	return 0
}

func (m *JointWrench) GetBody_1Wrench() *Wrench {
	if m != nil {
		return m.Body_1Wrench
	}
	return nil
}

func (m *JointWrench) GetBody_2Wrench() *Wrench {
	if m != nil {
		return m.Body_2Wrench
	}
	return nil
}

func init() {
	proto.RegisterType((*JointWrench)(nil), "gazebo.msgs.JointWrench")
}

func init() { proto.RegisterFile("joint_wrench.proto", fileDescriptor45) }

var fileDescriptor45 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xca, 0xcf, 0xcc,
	0x2b, 0x89, 0x2f, 0x2f, 0x4a, 0xcd, 0x4b, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x96, 0xe2, 0x41, 0x96, 0x52,
	0xda, 0xca, 0xc8, 0xc5, 0xed, 0x05, 0xd2, 0x11, 0x0e, 0x16, 0x15, 0x12, 0xe6, 0xe2, 0x4e, 0xca,
	0x4f, 0xa9, 0x8c, 0x37, 0x8c, 0xcf, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x14,
	0x12, 0xe4, 0xe2, 0x84, 0x0a, 0x66, 0xa6, 0x48, 0x30, 0x01, 0x85, 0x78, 0xe1, 0xea, 0x8c, 0x20,
	0xea, 0x98, 0x51, 0xd4, 0x19, 0x81, 0xd4, 0xb1, 0x80, 0xd5, 0x69, 0x71, 0xf1, 0x42, 0xb5, 0x42,
	0xac, 0x95, 0x60, 0x05, 0x0a, 0x73, 0x1b, 0x09, 0xeb, 0x21, 0x39, 0x49, 0x0f, 0x6a, 0x37, 0x4c,
	0xad, 0x11, 0x4c, 0x2d, 0x1b, 0x4e, 0xb5, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xbc, 0xd6,
	0xe8, 0xe7, 0x00, 0x00, 0x00,
}
