// Code generated by protoc-gen-go.
// source: pid.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PID struct {
	Target           *float64 `protobuf:"fixed64,1,opt,name=target,def=0" json:"target,omitempty"`
	PGain            *float64 `protobuf:"fixed64,2,opt,name=p_gain,def=0" json:"p_gain,omitempty"`
	IGain            *float64 `protobuf:"fixed64,3,opt,name=i_gain,def=0" json:"i_gain,omitempty"`
	DGain            *float64 `protobuf:"fixed64,4,opt,name=d_gain,def=0" json:"d_gain,omitempty"`
	IMax             *float64 `protobuf:"fixed64,5,opt,name=i_max,def=0" json:"i_max,omitempty"`
	IMin             *float64 `protobuf:"fixed64,6,opt,name=i_min,def=0" json:"i_min,omitempty"`
	Limit            *float64 `protobuf:"fixed64,7,opt,name=limit,def=0" json:"limit,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PID) Reset()                    { *m = PID{} }
func (m *PID) String() string            { return proto.CompactTextString(m) }
func (*PID) ProtoMessage()               {}
func (*PID) Descriptor() ([]byte, []int) { return fileDescriptor69, []int{0} }

const Default_PID_Target float64 = 0
const Default_PID_PGain float64 = 0
const Default_PID_IGain float64 = 0
const Default_PID_DGain float64 = 0
const Default_PID_IMax float64 = 0
const Default_PID_IMin float64 = 0
const Default_PID_Limit float64 = 0

func (m *PID) GetTarget() float64 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return Default_PID_Target
}

func (m *PID) GetPGain() float64 {
	if m != nil && m.PGain != nil {
		return *m.PGain
	}
	return Default_PID_PGain
}

func (m *PID) GetIGain() float64 {
	if m != nil && m.IGain != nil {
		return *m.IGain
	}
	return Default_PID_IGain
}

func (m *PID) GetDGain() float64 {
	if m != nil && m.DGain != nil {
		return *m.DGain
	}
	return Default_PID_DGain
}

func (m *PID) GetIMax() float64 {
	if m != nil && m.IMax != nil {
		return *m.IMax
	}
	return Default_PID_IMax
}

func (m *PID) GetIMin() float64 {
	if m != nil && m.IMin != nil {
		return *m.IMin
	}
	return Default_PID_IMin
}

func (m *PID) GetLimit() float64 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return Default_PID_Limit
}

func init() {
	proto.RegisterType((*PID)(nil), "gazebo.msgs.PID")
}

func init() { proto.RegisterFile("pid.proto", fileDescriptor69) }

var fileDescriptor69 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0xc8, 0x4c, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d,
	0x4e, 0x2f, 0x56, 0x6a, 0x67, 0xe4, 0x62, 0x0e, 0xf0, 0x74, 0x11, 0x12, 0xe4, 0x62, 0x2b, 0x49,
	0x2c, 0x4a, 0x4f, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0xb4, 0x62, 0x34, 0x00, 0x09, 0x15,
	0xc4, 0xa7, 0x27, 0x66, 0xe6, 0x49, 0x30, 0x21, 0x09, 0x65, 0x42, 0x84, 0x98, 0x91, 0x84, 0x52,
	0x20, 0x42, 0x2c, 0x30, 0x21, 0x01, 0x2e, 0xd6, 0xcc, 0xf8, 0xdc, 0xc4, 0x0a, 0x09, 0x56, 0x54,
	0x11, 0xa0, 0x1a, 0x36, 0x24, 0x91, 0x9c, 0xcc, 0xdc, 0xcc, 0x12, 0x09, 0x76, 0xa8, 0x08, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x83, 0x18, 0x7d, 0x46, 0xa2, 0x00, 0x00, 0x00,
}
