// Code generated by protoc-gen-go.
// source: plugin.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Plugin struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Filename         *string `protobuf:"bytes,2,req,name=filename" json:"filename,omitempty"`
	Innerxml         *string `protobuf:"bytes,3,opt,name=innerxml,def=" json:"innerxml,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Plugin) Reset()                    { *m = Plugin{} }
func (m *Plugin) String() string            { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()               {}
func (*Plugin) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{0} }

func (m *Plugin) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Plugin) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *Plugin) GetInnerxml() string {
	if m != nil && m.Innerxml != nil {
		return *m.Innerxml
	}
	return ""
}

func init() {
	proto.RegisterType((*Plugin)(nil), "gazebo.msgs.Plugin")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor71) }

var fileDescriptor71 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc8, 0x29, 0x4d,
	0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca,
	0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0xb2, 0xe1, 0x62, 0x0b, 0x00, 0x4b, 0x0a, 0xf1, 0x70, 0xb1,
	0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0x70, 0x0a, 0x09, 0x70, 0x71, 0xa4, 0x65,
	0xe6, 0xa4, 0x82, 0x45, 0x98, 0xc0, 0x22, 0x42, 0x5c, 0x1c, 0x99, 0x79, 0x79, 0xa9, 0x45, 0x15,
	0xb9, 0x39, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x56, 0x0c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xe7, 0x97, 0xfb, 0xd3, 0x59, 0x00, 0x00, 0x00,
}
