// Code generated by protoc-gen-go.
// source: propagation_particle.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PropagationParticle struct {
	X                *float64 `protobuf:"fixed64,1,req,name=x" json:"x,omitempty"`
	Y                *float64 `protobuf:"fixed64,2,req,name=y" json:"y,omitempty"`
	SignalLevel      *float64 `protobuf:"fixed64,3,req,name=signal_level" json:"signal_level,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PropagationParticle) Reset()                    { *m = PropagationParticle{} }
func (m *PropagationParticle) String() string            { return proto.CompactTextString(m) }
func (*PropagationParticle) ProtoMessage()               {}
func (*PropagationParticle) Descriptor() ([]byte, []int) { return fileDescriptor82, []int{0} }

func (m *PropagationParticle) GetX() float64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PropagationParticle) GetY() float64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *PropagationParticle) GetSignalLevel() float64 {
	if m != nil && m.SignalLevel != nil {
		return *m.SignalLevel
	}
	return 0
}

func init() {
	proto.RegisterType((*PropagationParticle)(nil), "gazebo.msgs.PropagationParticle")
}

func init() { proto.RegisterFile("propagation_particle.proto", fileDescriptor82) }

var fileDescriptor82 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0x48, 0x4c, 0x4f, 0x2c, 0xc9, 0xcc, 0xcf, 0x8b, 0x2f, 0x48, 0x2c, 0x2a, 0xc9, 0x4c, 0xce, 0x49,
	0xd5, 0x03, 0x0a, 0x96, 0xe4, 0x0b, 0x71, 0xa7, 0x27, 0x56, 0xa5, 0x26, 0xe5, 0xeb, 0xe5, 0x16,
	0xa7, 0x17, 0x2b, 0x39, 0x72, 0x09, 0x07, 0x20, 0x94, 0x06, 0x40, 0x55, 0x0a, 0x71, 0x72, 0x31,
	0x56, 0x48, 0x30, 0x2a, 0x30, 0x69, 0x30, 0x82, 0x98, 0x95, 0x12, 0x4c, 0x60, 0xa6, 0x08, 0x17,
	0x4f, 0x71, 0x66, 0x7a, 0x5e, 0x62, 0x4e, 0x7c, 0x4e, 0x6a, 0x59, 0x6a, 0x8e, 0x04, 0x33, 0x48,
	0x14, 0x10, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xf9, 0x08, 0xf5, 0x6c, 0x00, 0x00, 0x00,
}
