// Code generated by protoc-gen-go.
// source: request.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Request struct {
	Id               *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *string  `protobuf:"bytes,2,req,name=request" json:"request,omitempty"`
	Data             *string  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	DblData          *float64 `protobuf:"fixed64,4,opt,name=dbl_data" json:"dbl_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor87, []int{0} }

func (m *Request) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Request) GetRequest() string {
	if m != nil && m.Request != nil {
		return *m.Request
	}
	return ""
}

func (m *Request) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *Request) GetDblData() float64 {
	if m != nil && m.DblData != nil {
		return *m.DblData
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "gazebo.msgs.Request")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor87) }

var fileDescriptor87 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d,
	0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x72, 0xe3, 0x62, 0x0f, 0x82, 0xc8, 0x0a, 0x71, 0x71,
	0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x0a, 0xf1, 0x73, 0xb1, 0x43, 0x35, 0x49,
	0x30, 0x01, 0x05, 0x38, 0x85, 0x78, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x15, 0x18,
	0x81, 0x3c, 0x01, 0x2e, 0x8e, 0x94, 0xa4, 0x9c, 0x78, 0xb0, 0x08, 0x0b, 0x50, 0x84, 0x11, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0xf8, 0x28, 0x69, 0x64, 0x00, 0x00, 0x00,
}
