// Code generated by protoc-gen-go.
// source: response.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Response struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Request          *string `protobuf:"bytes,2,req,name=request" json:"request,omitempty"`
	Response         *string `protobuf:"bytes,3,req,name=response" json:"response,omitempty"`
	Type             *string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	SerializedData   []byte  `protobuf:"bytes,5,opt,name=serialized_data" json:"serialized_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor88, []int{0} }

func (m *Response) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Response) GetRequest() string {
	if m != nil && m.Request != nil {
		return *m.Request
	}
	return ""
}

func (m *Response) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func (m *Response) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Response) GetSerializedData() []byte {
	if m != nil {
		return m.SerializedData
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "gazebo.msgs.Response")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor88) }

var fileDescriptor88 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a,
	0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x4a, 0xe0, 0xe2, 0x08, 0x82, 0x4a, 0x0b, 0x71,
	0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x0a, 0xf1, 0x73, 0xb1, 0x17, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x48, 0x30, 0x01, 0x05, 0x38, 0x85, 0x04, 0xb8, 0x38, 0x60, 0xe6,
	0x48, 0x30, 0x83, 0x45, 0x78, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x58, 0x14, 0x18, 0x81,
	0x3c, 0x71, 0x2e, 0xfe, 0xe2, 0xd4, 0xa2, 0xcc, 0xc4, 0x9c, 0xcc, 0xaa, 0xd4, 0x94, 0xf8, 0x94,
	0xc4, 0x92, 0x44, 0x09, 0x56, 0xa0, 0x04, 0x0f, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x6b, 0xfd,
	0xcf, 0x7f, 0x00, 0x00, 0x00,
}
