// Code generated by protoc-gen-go.
// source: rest_logout.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RestLogout struct {
	// / \brief ID of this request message
	Id *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// / \brief the web service url
	Url              *string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RestLogout) Reset()                    { *m = RestLogout{} }
func (m *RestLogout) String() string            { return proto.CompactTextString(m) }
func (*RestLogout) ProtoMessage()               {}
func (*RestLogout) Descriptor() ([]byte, []int) { return fileDescriptor90, []int{0} }

func (m *RestLogout) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RestLogout) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*RestLogout)(nil), "gazebo.msgs.RestLogout")
}

func init() { proto.RegisterFile("rest_logout.proto", fileDescriptor90) }

var fileDescriptor90 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4a, 0x2d, 0x2e,
	0x89, 0xcf, 0xc9, 0x4f, 0xcf, 0x2f, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e,
	0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x52, 0xe5, 0xe2, 0x0a, 0x02,
	0xaa, 0xf0, 0x01, 0x2b, 0x10, 0xe2, 0xe2, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x15, 0xe2, 0xe6, 0x62, 0x2e, 0x2d, 0xca, 0x91, 0x60, 0x02, 0x72, 0x38, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x83, 0x4f, 0x0a, 0xf2, 0x47, 0x00, 0x00, 0x00,
}
