// Code generated by protoc-gen-go.
// source: rest_response.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RestResponse_Type int32

const (
	// / \brief Rest service call was successfull
	RestResponse_SUCCESS RestResponse_Type = 1
	// / \brief Error calling rest service
	RestResponse_ERR RestResponse_Type = 2
	// / \brief Response to a login request
	RestResponse_LOGIN RestResponse_Type = 3
	// / \brief Response to a logout request
	RestResponse_LOGOUT RestResponse_Type = 4
)

var RestResponse_Type_name = map[int32]string{
	1: "SUCCESS",
	2: "ERR",
	3: "LOGIN",
	4: "LOGOUT",
}
var RestResponse_Type_value = map[string]int32{
	"SUCCESS": 1,
	"ERR":     2,
	"LOGIN":   3,
	"LOGOUT":  4,
}

func (x RestResponse_Type) Enum() *RestResponse_Type {
	p := new(RestResponse_Type)
	*p = x
	return p
}
func (x RestResponse_Type) String() string {
	return proto.EnumName(RestResponse_Type_name, int32(x))
}
func (x *RestResponse_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RestResponse_Type_value, data, "RestResponse_Type")
	if err != nil {
		return err
	}
	*x = RestResponse_Type(value)
	return nil
}
func (RestResponse_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor92, []int{0, 0} }

type RestResponse struct {
	// / \brief ID of the response message
	Id *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// / \brief Type of response
	Type *RestResponse_Type `protobuf:"varint,2,req,name=type,enum=gazebo.msgs.RestResponse_Type" json:"type,omitempty"`
	// / \brief Message describing the response
	Msg              *string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RestResponse) Reset()                    { *m = RestResponse{} }
func (m *RestResponse) String() string            { return proto.CompactTextString(m) }
func (*RestResponse) ProtoMessage()               {}
func (*RestResponse) Descriptor() ([]byte, []int) { return fileDescriptor92, []int{0} }

func (m *RestResponse) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RestResponse) GetType() RestResponse_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RestResponse_SUCCESS
}

func (m *RestResponse) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RestResponse)(nil), "gazebo.msgs.RestResponse")
	proto.RegisterEnum("gazebo.msgs.RestResponse_Type", RestResponse_Type_name, RestResponse_Type_value)
}

func init() { proto.RegisterFile("rest_response.proto", fileDescriptor92) }

var fileDescriptor92 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4a, 0x2d, 0x2e,
	0x89, 0x07, 0x12, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xdc,
	0xe9, 0x89, 0x55, 0xa9, 0x49, 0xf9, 0x7a, 0xb9, 0xc5, 0xe9, 0xc5, 0x4a, 0x5d, 0x8c, 0x5c, 0x3c,
	0x41, 0x40, 0x45, 0x41, 0x50, 0x35, 0x42, 0x5c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xbc, 0x42, 0x3a, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x4c, 0x0a, 0x4c, 0x1a, 0x7c,
	0x46, 0x72, 0x7a, 0x48, 0x1a, 0xf5, 0x90, 0x35, 0xe9, 0x85, 0x00, 0x55, 0x09, 0x71, 0x73, 0x31,
	0x03, 0x65, 0x24, 0x98, 0x81, 0x5a, 0x39, 0x95, 0x8c, 0xb9, 0x58, 0xa0, 0x82, 0xec, 0xc1, 0xa1,
	0xce, 0xce, 0xae, 0xc1, 0xc1, 0x02, 0x8c, 0x42, 0xec, 0x5c, 0xcc, 0xae, 0x41, 0x41, 0x02, 0x4c,
	0x42, 0x9c, 0x5c, 0xac, 0x3e, 0xfe, 0xee, 0x9e, 0x7e, 0x02, 0xcc, 0x40, 0xfb, 0xd8, 0x80, 0x4c,
	0xff, 0xd0, 0x10, 0x01, 0x16, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xb4, 0x2a, 0x15, 0xaf,
	0x00, 0x00, 0x00,
}
