// Code generated by protoc-gen-go.
// source: selection.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Selection struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Selected         *bool   `protobuf:"varint,3,opt,name=selected,def=0" json:"selected,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Selection) Reset()                    { *m = Selection{} }
func (m *Selection) String() string            { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()               {}
func (*Selection) Descriptor() ([]byte, []int) { return fileDescriptor95, []int{0} }

const Default_Selection_Selected bool = false

func (m *Selection) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Selection) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Selection) GetSelected() bool {
	if m != nil && m.Selected != nil {
		return *m.Selected
	}
	return Default_Selection_Selected
}

func init() {
	proto.RegisterType((*Selection)(nil), "gazebo.msgs.Selection")
}

func init() { proto.RegisterFile("selection.proto", fileDescriptor95) }

var fileDescriptor95 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4e, 0xcd, 0x49,
	0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac,
	0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0xb2, 0xe3, 0xe2, 0x0c, 0x86, 0xc9, 0x0b,
	0x71, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xf0, 0x0a, 0xf1, 0x70, 0xb1, 0xe4,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x01, 0x79, 0x9c, 0x42, 0xe2, 0x5c, 0x1c, 0x10, 0x63, 0x52, 0x53,
	0x24, 0x98, 0x15, 0x18, 0x35, 0x38, 0xac, 0x58, 0xd3, 0x12, 0x73, 0x8a, 0x53, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x48, 0x2a, 0xa0, 0x91, 0x5e, 0x00, 0x00, 0x00,
}
