// Code generated by protoc-gen-go.
// source: spheregeom.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SphereGeom struct {
	// / \brief Radius of the sphere.
	Radius           *float64 `protobuf:"fixed64,1,req,name=radius" json:"radius,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SphereGeom) Reset()                    { *m = SphereGeom{} }
func (m *SphereGeom) String() string            { return proto.CompactTextString(m) }
func (*SphereGeom) ProtoMessage()               {}
func (*SphereGeom) Descriptor() ([]byte, []int) { return fileDescriptor104, []int{0} }

func (m *SphereGeom) GetRadius() float64 {
	if m != nil && m.Radius != nil {
		return *m.Radius
	}
	return 0
}

func init() {
	proto.RegisterType((*SphereGeom)(nil), "gazebo.msgs.SphereGeom")
}

func init() { proto.RegisterFile("spheregeom.proto", fileDescriptor104) }

var fileDescriptor104 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2e, 0xc8, 0x48,
	0x2d, 0x4a, 0x4d, 0x4f, 0xcd, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f,
	0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x92, 0xe1, 0xe2, 0x0a, 0x06, 0x2b,
	0x70, 0x07, 0x2a, 0x10, 0xe2, 0xe3, 0x62, 0x2b, 0x4a, 0x4c, 0xc9, 0x2c, 0x2d, 0x96, 0x60, 0x54,
	0x60, 0xd2, 0x60, 0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0x16, 0x10, 0x3e, 0x65, 0x3d, 0x00, 0x00,
	0x00,
}
