// Code generated by protoc-gen-go.
// source: empty.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Empty struct {
	Unused           *bool  `protobuf:"varint,1,opt,name=unused" json:"unused,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor19, []int{0} }

func (m *Empty) GetUnused() bool {
	if m != nil && m.Unused != nil {
		return *m.Unused
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "gazebo.msgs.Empty")
}

func init() { proto.RegisterFile("empty.proto", fileDescriptor19) }

var fileDescriptor19 = []byte{
	// 73 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x2d, 0x28,
	0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7,
	0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x12, 0xe7, 0x62, 0x75, 0x05, 0xc9, 0x09, 0xf1, 0x71, 0xb1, 0x95,
	0xe6, 0x95, 0x16, 0xa7, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x00, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x90, 0x00, 0xe3, 0xe6, 0x33, 0x00, 0x00, 0x00,
}
