// Code generated by protoc-gen-go.
// source: inertial.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Inertial struct {
	Mass             *float64 `protobuf:"fixed64,1,opt,name=mass" json:"mass,omitempty"`
	Pose             *Pose    `protobuf:"bytes,2,opt,name=pose" json:"pose,omitempty"`
	Ixx              *float64 `protobuf:"fixed64,3,opt,name=ixx" json:"ixx,omitempty"`
	Ixy              *float64 `protobuf:"fixed64,4,opt,name=ixy" json:"ixy,omitempty"`
	Ixz              *float64 `protobuf:"fixed64,5,opt,name=ixz" json:"ixz,omitempty"`
	Iyy              *float64 `protobuf:"fixed64,6,opt,name=iyy" json:"iyy,omitempty"`
	Iyz              *float64 `protobuf:"fixed64,7,opt,name=iyz" json:"iyz,omitempty"`
	Izz              *float64 `protobuf:"fixed64,8,opt,name=izz" json:"izz,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Inertial) Reset()                    { *m = Inertial{} }
func (m *Inertial) String() string            { return proto.CompactTextString(m) }
func (*Inertial) ProtoMessage()               {}
func (*Inertial) Descriptor() ([]byte, []int) { return fileDescriptor40, []int{0} }

func (m *Inertial) GetMass() float64 {
	if m != nil && m.Mass != nil {
		return *m.Mass
	}
	return 0
}

func (m *Inertial) GetPose() *Pose {
	if m != nil {
		return m.Pose
	}
	return nil
}

func (m *Inertial) GetIxx() float64 {
	if m != nil && m.Ixx != nil {
		return *m.Ixx
	}
	return 0
}

func (m *Inertial) GetIxy() float64 {
	if m != nil && m.Ixy != nil {
		return *m.Ixy
	}
	return 0
}

func (m *Inertial) GetIxz() float64 {
	if m != nil && m.Ixz != nil {
		return *m.Ixz
	}
	return 0
}

func (m *Inertial) GetIyy() float64 {
	if m != nil && m.Iyy != nil {
		return *m.Iyy
	}
	return 0
}

func (m *Inertial) GetIyz() float64 {
	if m != nil && m.Iyz != nil {
		return *m.Iyz
	}
	return 0
}

func (m *Inertial) GetIzz() float64 {
	if m != nil && m.Izz != nil {
		return *m.Izz
	}
	return 0
}

func init() {
	proto.RegisterType((*Inertial)(nil), "gazebo.msgs.Inertial")
}

func init() { proto.RegisterFile("inertial.proto", fileDescriptor40) }

var fileDescriptor40 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x4b, 0x2d,
	0x2a, 0xc9, 0x4c, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a,
	0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x96, 0xe2, 0x2a, 0xc8, 0x2f, 0x4e, 0x85, 0x48, 0x28,
	0xb5, 0x33, 0x72, 0x71, 0x78, 0x42, 0xd5, 0x0a, 0xf1, 0x70, 0xb1, 0xe4, 0x26, 0x16, 0x17, 0x4b,
	0x30, 0x2a, 0x30, 0x6a, 0x30, 0x0a, 0xc9, 0x73, 0xb1, 0x80, 0x14, 0x4a, 0x30, 0x01, 0x79, 0xdc,
	0x46, 0x82, 0x7a, 0x48, 0x46, 0xe8, 0x05, 0x00, 0x25, 0x84, 0xb8, 0xb9, 0x98, 0x33, 0x2b, 0x2a,
	0x24, 0x98, 0xc1, 0xaa, 0xc1, 0x9c, 0x4a, 0x09, 0x16, 0x04, 0xa7, 0x4a, 0x82, 0x15, 0xce, 0xa9,
	0xac, 0x94, 0x60, 0x43, 0x70, 0xaa, 0x24, 0xd8, 0xe1, 0x9c, 0xaa, 0x2a, 0x09, 0x0e, 0x10, 0x07,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x28, 0xa6, 0x82, 0xb3, 0x00, 0x00, 0x00,
}
