// Code generated by protoc-gen-go.
// source: joint_animation.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type JointAnimation struct {
	ModelName        *string                 `protobuf:"bytes,1,req,name=model_name" json:"model_name,omitempty"`
	Joint            []*JointAnimation_Joint `protobuf:"bytes,2,rep,name=joint" json:"joint,omitempty"`
	Time             []*Time                 `protobuf:"bytes,3,rep,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *JointAnimation) Reset()                    { *m = JointAnimation{} }
func (m *JointAnimation) String() string            { return proto.CompactTextString(m) }
func (*JointAnimation) ProtoMessage()               {}
func (*JointAnimation) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{0} }

func (m *JointAnimation) GetModelName() string {
	if m != nil && m.ModelName != nil {
		return *m.ModelName
	}
	return ""
}

func (m *JointAnimation) GetJoint() []*JointAnimation_Joint {
	if m != nil {
		return m.Joint
	}
	return nil
}

func (m *JointAnimation) GetTime() []*Time {
	if m != nil {
		return m.Time
	}
	return nil
}

type JointAnimation_Joint struct {
	Name             []string  `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	Angle            []float64 `protobuf:"fixed64,2,rep,name=angle" json:"angle,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *JointAnimation_Joint) Reset()                    { *m = JointAnimation_Joint{} }
func (m *JointAnimation_Joint) String() string            { return proto.CompactTextString(m) }
func (*JointAnimation_Joint) ProtoMessage()               {}
func (*JointAnimation_Joint) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{0, 0} }

func (m *JointAnimation_Joint) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *JointAnimation_Joint) GetAngle() []float64 {
	if m != nil {
		return m.Angle
	}
	return nil
}

func init() {
	proto.RegisterType((*JointAnimation)(nil), "gazebo.msgs.JointAnimation")
	proto.RegisterType((*JointAnimation_Joint)(nil), "gazebo.msgs.JointAnimation.Joint")
}

func init() { proto.RegisterFile("joint_animation.proto", fileDescriptor42) }

var fileDescriptor42 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0xca, 0xcf, 0xcc,
	0x2b, 0x89, 0x4f, 0xcc, 0xcb, 0xcc, 0x4d, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x96, 0xe2,
	0x2a, 0xc9, 0xcc, 0x4d, 0x85, 0x48, 0x28, 0xcd, 0x65, 0xe4, 0xe2, 0xf3, 0x02, 0x69, 0x71, 0x84,
	0xe9, 0x10, 0x12, 0xe2, 0xe2, 0xca, 0xcd, 0x4f, 0x49, 0xcd, 0x89, 0xcf, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd2, 0xe0, 0x14, 0x32, 0xe0, 0x62, 0x05, 0x1b, 0x2c, 0xc1, 0xa4, 0xc0, 0xac,
	0xc1, 0x6d, 0xa4, 0xa8, 0x87, 0x64, 0x9e, 0x1e, 0xaa, 0x7e, 0x08, 0x57, 0x48, 0x9e, 0x8b, 0x05,
	0x64, 0x8d, 0x04, 0x33, 0x58, 0x83, 0x20, 0x8a, 0x86, 0x10, 0xa0, 0x84, 0x94, 0x0a, 0x17, 0x2b,
	0x44, 0x25, 0x0f, 0x17, 0x0b, 0xd4, 0x26, 0x66, 0xa0, 0x4d, 0xbc, 0x5c, 0xac, 0x89, 0x79, 0xe9,
	0x39, 0xa9, 0x60, 0x9b, 0x18, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0x61, 0x89, 0x3e, 0xd0,
	0x00, 0x00, 0x00,
}
