// Code generated by protoc-gen-go.
// source: log_status.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LogStatus_LogFile_Units int32

const (
	LogStatus_LogFile_BYTES   LogStatus_LogFile_Units = 1
	LogStatus_LogFile_K_BYTES LogStatus_LogFile_Units = 2
	LogStatus_LogFile_M_BYTES LogStatus_LogFile_Units = 3
	LogStatus_LogFile_G_BYTES LogStatus_LogFile_Units = 4
)

var LogStatus_LogFile_Units_name = map[int32]string{
	1: "BYTES",
	2: "K_BYTES",
	3: "M_BYTES",
	4: "G_BYTES",
}
var LogStatus_LogFile_Units_value = map[string]int32{
	"BYTES":   1,
	"K_BYTES": 2,
	"M_BYTES": 3,
	"G_BYTES": 4,
}

func (x LogStatus_LogFile_Units) Enum() *LogStatus_LogFile_Units {
	p := new(LogStatus_LogFile_Units)
	*p = x
	return p
}
func (x LogStatus_LogFile_Units) String() string {
	return proto.EnumName(LogStatus_LogFile_Units_name, int32(x))
}
func (x *LogStatus_LogFile_Units) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LogStatus_LogFile_Units_value, data, "LogStatus_LogFile_Units")
	if err != nil {
		return err
	}
	*x = LogStatus_LogFile_Units(value)
	return nil
}
func (LogStatus_LogFile_Units) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor58, []int{0, 0, 0}
}

type LogStatus struct {
	SimTime          *Time              `protobuf:"bytes,1,opt,name=sim_time" json:"sim_time,omitempty"`
	LogFile          *LogStatus_LogFile `protobuf:"bytes,2,opt,name=log_file" json:"log_file,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *LogStatus) Reset()                    { *m = LogStatus{} }
func (m *LogStatus) String() string            { return proto.CompactTextString(m) }
func (*LogStatus) ProtoMessage()               {}
func (*LogStatus) Descriptor() ([]byte, []int) { return fileDescriptor58, []int{0} }

func (m *LogStatus) GetSimTime() *Time {
	if m != nil {
		return m.SimTime
	}
	return nil
}

func (m *LogStatus) GetLogFile() *LogStatus_LogFile {
	if m != nil {
		return m.LogFile
	}
	return nil
}

type LogStatus_LogFile struct {
	Uri              *string                  `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	BasePath         *string                  `protobuf:"bytes,2,opt,name=base_path" json:"base_path,omitempty"`
	FullPath         *string                  `protobuf:"bytes,3,opt,name=full_path" json:"full_path,omitempty"`
	Size             *float32                 `protobuf:"fixed32,4,opt,name=size" json:"size,omitempty"`
	SizeUnits        *LogStatus_LogFile_Units `protobuf:"varint,5,opt,name=size_units,enum=gazebo.msgs.LogStatus_LogFile_Units" json:"size_units,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *LogStatus_LogFile) Reset()                    { *m = LogStatus_LogFile{} }
func (m *LogStatus_LogFile) String() string            { return proto.CompactTextString(m) }
func (*LogStatus_LogFile) ProtoMessage()               {}
func (*LogStatus_LogFile) Descriptor() ([]byte, []int) { return fileDescriptor58, []int{0, 0} }

func (m *LogStatus_LogFile) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *LogStatus_LogFile) GetBasePath() string {
	if m != nil && m.BasePath != nil {
		return *m.BasePath
	}
	return ""
}

func (m *LogStatus_LogFile) GetFullPath() string {
	if m != nil && m.FullPath != nil {
		return *m.FullPath
	}
	return ""
}

func (m *LogStatus_LogFile) GetSize() float32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *LogStatus_LogFile) GetSizeUnits() LogStatus_LogFile_Units {
	if m != nil && m.SizeUnits != nil {
		return *m.SizeUnits
	}
	return LogStatus_LogFile_BYTES
}

func init() {
	proto.RegisterType((*LogStatus)(nil), "gazebo.msgs.LogStatus")
	proto.RegisterType((*LogStatus_LogFile)(nil), "gazebo.msgs.LogStatus.LogFile")
	proto.RegisterEnum("gazebo.msgs.LogStatus_LogFile_Units", LogStatus_LogFile_Units_name, LogStatus_LogFile_Units_value)
}

func init() { proto.RegisterFile("log_status.proto", fileDescriptor58) }

var fileDescriptor58 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xc9, 0x4f, 0x8f,
	0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f,
	0xac, 0x4a, 0x4d, 0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x96, 0xe2, 0x2a, 0xc9, 0xcc, 0x4d, 0x85,
	0x48, 0x28, 0x2d, 0x61, 0xe2, 0xe2, 0xf4, 0xc9, 0x4f, 0x0f, 0x06, 0x2b, 0x16, 0x52, 0xe6, 0xe2,
	0x28, 0xce, 0xcc, 0x8d, 0x07, 0xc9, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x09, 0xea, 0x21,
	0xe9, 0xd4, 0x0b, 0x01, 0x4a, 0x08, 0x19, 0x70, 0x71, 0x80, 0xcc, 0x4f, 0xcb, 0xcc, 0x49, 0x95,
	0x60, 0x02, 0x2b, 0x92, 0x43, 0x51, 0x04, 0x37, 0x0e, 0xc4, 0x72, 0x03, 0xaa, 0x92, 0xda, 0xcf,
	0xc8, 0xc5, 0x0e, 0x65, 0x0b, 0x71, 0x73, 0x31, 0x97, 0x16, 0x65, 0x82, 0x4d, 0xe7, 0x14, 0x12,
	0xe4, 0xe2, 0x4c, 0x4a, 0x2c, 0x4e, 0x8d, 0x2f, 0x48, 0x2c, 0xc9, 0x00, 0x9b, 0x05, 0x16, 0x4a,
	0x2b, 0xcd, 0xc9, 0x81, 0x08, 0x31, 0x83, 0x85, 0x78, 0xb8, 0x58, 0x8a, 0x33, 0xab, 0x52, 0x25,
	0x58, 0x80, 0x3c, 0x26, 0x21, 0x0b, 0x2e, 0x2e, 0x10, 0x2f, 0xbe, 0x34, 0x2f, 0xb3, 0xa4, 0x58,
	0x82, 0x15, 0x28, 0xc6, 0x67, 0xa4, 0x82, 0xdf, 0x01, 0x7a, 0xa1, 0x20, 0xb5, 0x4a, 0x96, 0x5c,
	0xac, 0x60, 0x86, 0x10, 0x27, 0x17, 0xab, 0x53, 0x64, 0x88, 0x6b, 0xb0, 0x00, 0x23, 0xd0, 0x39,
	0xec, 0xde, 0xf1, 0x10, 0x0e, 0x13, 0x88, 0xe3, 0x0b, 0xe5, 0x30, 0x83, 0x38, 0xee, 0x50, 0x0e,
	0x0b, 0x20, 0x00, 0x00, 0xff, 0xff, 0x33, 0x36, 0x62, 0x1b, 0x52, 0x01, 0x00, 0x00,
}
