// Code generated by protoc-gen-go.
// source: publish.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Publish struct {
	Topic            *string `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	MsgType          *string `protobuf:"bytes,2,req,name=msg_type" json:"msg_type,omitempty"`
	Host             *string `protobuf:"bytes,3,req,name=host" json:"host,omitempty"`
	Port             *uint32 `protobuf:"varint,4,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Publish) Reset()                    { *m = Publish{} }
func (m *Publish) String() string            { return proto.CompactTextString(m) }
func (*Publish) ProtoMessage()               {}
func (*Publish) Descriptor() ([]byte, []int) { return fileDescriptor84, []int{0} }

func (m *Publish) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *Publish) GetMsgType() string {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return ""
}

func (m *Publish) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *Publish) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*Publish)(nil), "gazebo.msgs.Publish")
}

func init() { proto.RegisterFile("publish.proto", fileDescriptor84) }

var fileDescriptor84 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0x4d, 0xca,
	0xc9, 0x2c, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d,
	0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0x72, 0xe3, 0x62, 0x0f, 0x80, 0xc8, 0x0a, 0xf1, 0x72,
	0xb1, 0x96, 0xe4, 0x17, 0x64, 0x26, 0x4b, 0x30, 0x2a, 0x30, 0x69, 0x70, 0x0a, 0x09, 0x70, 0x71,
	0x00, 0x55, 0xc4, 0x97, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x81, 0x45, 0x78, 0xb8, 0x58, 0x32, 0xf2,
	0x8b, 0x4b, 0x24, 0x98, 0x61, 0xbc, 0x82, 0xfc, 0xa2, 0x12, 0x09, 0x16, 0x20, 0x8f, 0x17, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xa8, 0x20, 0x74, 0x08, 0x64, 0x00, 0x00, 0x00,
}
