// Code generated by protoc-gen-go.
// source: server_control.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ServerControl struct {
	SaveWorldName    *string `protobuf:"bytes,1,opt,name=save_world_name" json:"save_world_name,omitempty"`
	SaveFilename     *string `protobuf:"bytes,2,opt,name=save_filename" json:"save_filename,omitempty"`
	OpenFilename     *string `protobuf:"bytes,3,opt,name=open_filename" json:"open_filename,omitempty"`
	NewWorld         *bool   `protobuf:"varint,4,opt,name=new_world" json:"new_world,omitempty"`
	Stop             *bool   `protobuf:"varint,5,opt,name=stop" json:"stop,omitempty"`
	Clone            *bool   `protobuf:"varint,6,opt,name=clone" json:"clone,omitempty"`
	NewPort          *uint32 `protobuf:"varint,7,opt,name=new_port" json:"new_port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerControl) Reset()                    { *m = ServerControl{} }
func (m *ServerControl) String() string            { return proto.CompactTextString(m) }
func (*ServerControl) ProtoMessage()               {}
func (*ServerControl) Descriptor() ([]byte, []int) { return fileDescriptor98, []int{0} }

func (m *ServerControl) GetSaveWorldName() string {
	if m != nil && m.SaveWorldName != nil {
		return *m.SaveWorldName
	}
	return ""
}

func (m *ServerControl) GetSaveFilename() string {
	if m != nil && m.SaveFilename != nil {
		return *m.SaveFilename
	}
	return ""
}

func (m *ServerControl) GetOpenFilename() string {
	if m != nil && m.OpenFilename != nil {
		return *m.OpenFilename
	}
	return ""
}

func (m *ServerControl) GetNewWorld() bool {
	if m != nil && m.NewWorld != nil {
		return *m.NewWorld
	}
	return false
}

func (m *ServerControl) GetStop() bool {
	if m != nil && m.Stop != nil {
		return *m.Stop
	}
	return false
}

func (m *ServerControl) GetClone() bool {
	if m != nil && m.Clone != nil {
		return *m.Clone
	}
	return false
}

func (m *ServerControl) GetNewPort() uint32 {
	if m != nil && m.NewPort != nil {
		return *m.NewPort
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerControl)(nil), "gazebo.msgs.ServerControl")
}

func init() { proto.RegisterFile("server_control.proto", fileDescriptor98) }

var fileDescriptor98 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xcc, 0x41, 0xaa, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0xfa, 0x5e, 0xab, 0xed, 0x68, 0x50, 0x83, 0x62, 0x96, 0xe2, 0xca, 0x55, 0x2f,
	0xe1, 0x11, 0x3c, 0x40, 0xa9, 0x75, 0x2c, 0x42, 0x9a, 0x09, 0x93, 0xd0, 0x82, 0x27, 0xf1, 0xb8,
	0xd6, 0x29, 0xe2, 0xf2, 0xfb, 0xcd, 0x9f, 0x81, 0x6d, 0x40, 0xee, 0x91, 0xab, 0x86, 0x5c, 0x64,
	0xb2, 0xa5, 0x67, 0x8a, 0xa4, 0x17, 0x6d, 0xfd, 0xc4, 0x2b, 0x95, 0x5d, 0x68, 0xc3, 0xf1, 0x95,
	0x80, 0xba, 0x48, 0x75, 0x9e, 0x22, 0xbd, 0x87, 0x55, 0xa8, 0x7b, 0xac, 0x06, 0x62, 0x7b, 0xab,
	0x5c, 0xdd, 0xa1, 0x49, 0x0e, 0xc9, 0xa9, 0xd0, 0x3b, 0x50, 0x72, 0xb8, 0x3f, 0x2c, 0x0a, 0xff,
	0x7d, 0x99, 0x3c, 0xba, 0x1f, 0xff, 0x0b, 0x6f, 0xa0, 0x70, 0x38, 0x4c, 0x5f, 0x4c, 0x3a, 0x52,
	0xae, 0x97, 0x90, 0x86, 0x48, 0xde, 0x64, 0xb2, 0x14, 0x64, 0x8d, 0x25, 0x87, 0x66, 0x26, 0x73,
	0x0d, 0xf9, 0xa7, 0xf7, 0xc4, 0xd1, 0xcc, 0x47, 0x51, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b,
	0xc6, 0x02, 0x3f, 0xbe, 0x00, 0x00, 0x00,
}
