// Code generated by protoc-gen-go.
// source: shadows.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Shadows_ShadowType int32

const (
	Shadows_STENCIL_ADDITIVE   Shadows_ShadowType = 1
	Shadows_STENCIL_MODULATIVE Shadows_ShadowType = 2
	Shadows_TEXTURE_ADDITIVE   Shadows_ShadowType = 3
	Shadows_TEXTURE_MODULATIVE Shadows_ShadowType = 4
)

var Shadows_ShadowType_name = map[int32]string{
	1: "STENCIL_ADDITIVE",
	2: "STENCIL_MODULATIVE",
	3: "TEXTURE_ADDITIVE",
	4: "TEXTURE_MODULATIVE",
}
var Shadows_ShadowType_value = map[string]int32{
	"STENCIL_ADDITIVE":   1,
	"STENCIL_MODULATIVE": 2,
	"TEXTURE_ADDITIVE":   3,
	"TEXTURE_MODULATIVE": 4,
}

func (x Shadows_ShadowType) Enum() *Shadows_ShadowType {
	p := new(Shadows_ShadowType)
	*p = x
	return p
}
func (x Shadows_ShadowType) String() string {
	return proto.EnumName(Shadows_ShadowType_name, int32(x))
}
func (x *Shadows_ShadowType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Shadows_ShadowType_value, data, "Shadows_ShadowType")
	if err != nil {
		return err
	}
	*x = Shadows_ShadowType(value)
	return nil
}
func (Shadows_ShadowType) EnumDescriptor() ([]byte, []int) { return fileDescriptor99, []int{0, 0} }

type Shadows struct {
	Type             *Shadows_ShadowType `protobuf:"varint,5,opt,name=type,enum=gazebo.msgs.Shadows_ShadowType" json:"type,omitempty"`
	Color            *Color              `protobuf:"bytes,6,opt,name=color" json:"color,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Shadows) Reset()                    { *m = Shadows{} }
func (m *Shadows) String() string            { return proto.CompactTextString(m) }
func (*Shadows) ProtoMessage()               {}
func (*Shadows) Descriptor() ([]byte, []int) { return fileDescriptor99, []int{0} }

func (m *Shadows) GetType() Shadows_ShadowType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Shadows_STENCIL_ADDITIVE
}

func (m *Shadows) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func init() {
	proto.RegisterType((*Shadows)(nil), "gazebo.msgs.Shadows")
	proto.RegisterEnum("gazebo.msgs.Shadows_ShadowType", Shadows_ShadowType_name, Shadows_ShadowType_value)
}

func init() { proto.RegisterFile("shadows.proto", fileDescriptor99) }

var fileDescriptor99 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xce, 0x48, 0x4c,
	0xc9, 0x2f, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d,
	0xca, 0xd7, 0xcb, 0x2d, 0x4e, 0x2f, 0x96, 0xe2, 0x4e, 0xce, 0xcf, 0xc9, 0x2f, 0x82, 0xc8, 0x28,
	0x1d, 0x65, 0xe4, 0x62, 0x0f, 0x86, 0xa8, 0x15, 0xd2, 0xe5, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x55, 0x60, 0xd4, 0xe0, 0x33, 0x92, 0xd7, 0x43, 0xd2, 0xa4, 0x07, 0x55, 0x03, 0xa5, 0x43,
	0x80, 0xca, 0x84, 0x14, 0xb9, 0x58, 0xc1, 0x26, 0x49, 0xb0, 0x01, 0xd5, 0x73, 0x1b, 0x09, 0xa1,
	0xa8, 0x77, 0x06, 0xc9, 0x28, 0x65, 0x70, 0x71, 0x21, 0x69, 0x10, 0xe1, 0x12, 0x08, 0x0e, 0x71,
	0xf5, 0x73, 0xf6, 0xf4, 0x89, 0x77, 0x74, 0x71, 0xf1, 0x0c, 0xf1, 0x0c, 0x73, 0x15, 0x60, 0x14,
	0x12, 0xe3, 0x12, 0x82, 0x89, 0xfa, 0xfa, 0xbb, 0x84, 0xfa, 0x38, 0x82, 0xc5, 0x99, 0x40, 0xaa,
	0x43, 0x5c, 0x23, 0x42, 0x42, 0x83, 0x5c, 0x11, 0xaa, 0x99, 0x41, 0xaa, 0x61, 0xa2, 0x48, 0xaa,
	0x59, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xff, 0x9c, 0xa8, 0xf1, 0x00, 0x00, 0x00,
}
