// Code generated by protoc-gen-go.
// source: spherical_coordinates.proto
// DO NOT EDIT!

package gazebo_msgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SphericalCoordinates_SurfaceModel int32

const (
	SphericalCoordinates_EARTH_WGS84 SphericalCoordinates_SurfaceModel = 1
)

var SphericalCoordinates_SurfaceModel_name = map[int32]string{
	1: "EARTH_WGS84",
}
var SphericalCoordinates_SurfaceModel_value = map[string]int32{
	"EARTH_WGS84": 1,
}

func (x SphericalCoordinates_SurfaceModel) Enum() *SphericalCoordinates_SurfaceModel {
	p := new(SphericalCoordinates_SurfaceModel)
	*p = x
	return p
}
func (x SphericalCoordinates_SurfaceModel) String() string {
	return proto.EnumName(SphericalCoordinates_SurfaceModel_name, int32(x))
}
func (x *SphericalCoordinates_SurfaceModel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SphericalCoordinates_SurfaceModel_value, data, "SphericalCoordinates_SurfaceModel")
	if err != nil {
		return err
	}
	*x = SphericalCoordinates_SurfaceModel(value)
	return nil
}
func (SphericalCoordinates_SurfaceModel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor105, []int{0, 0}
}

type SphericalCoordinates struct {
	SurfaceModel     *SphericalCoordinates_SurfaceModel `protobuf:"varint,1,req,name=surface_model,enum=gazebo.msgs.SphericalCoordinates_SurfaceModel" json:"surface_model,omitempty"`
	LatitudeDeg      *float64                           `protobuf:"fixed64,2,req,name=latitude_deg" json:"latitude_deg,omitempty"`
	LongitudeDeg     *float64                           `protobuf:"fixed64,3,req,name=longitude_deg" json:"longitude_deg,omitempty"`
	Elevation        *float64                           `protobuf:"fixed64,4,req,name=elevation" json:"elevation,omitempty"`
	HeadingDeg       *float64                           `protobuf:"fixed64,5,req,name=heading_deg" json:"heading_deg,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *SphericalCoordinates) Reset()                    { *m = SphericalCoordinates{} }
func (m *SphericalCoordinates) String() string            { return proto.CompactTextString(m) }
func (*SphericalCoordinates) ProtoMessage()               {}
func (*SphericalCoordinates) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{0} }

func (m *SphericalCoordinates) GetSurfaceModel() SphericalCoordinates_SurfaceModel {
	if m != nil && m.SurfaceModel != nil {
		return *m.SurfaceModel
	}
	return SphericalCoordinates_EARTH_WGS84
}

func (m *SphericalCoordinates) GetLatitudeDeg() float64 {
	if m != nil && m.LatitudeDeg != nil {
		return *m.LatitudeDeg
	}
	return 0
}

func (m *SphericalCoordinates) GetLongitudeDeg() float64 {
	if m != nil && m.LongitudeDeg != nil {
		return *m.LongitudeDeg
	}
	return 0
}

func (m *SphericalCoordinates) GetElevation() float64 {
	if m != nil && m.Elevation != nil {
		return *m.Elevation
	}
	return 0
}

func (m *SphericalCoordinates) GetHeadingDeg() float64 {
	if m != nil && m.HeadingDeg != nil {
		return *m.HeadingDeg
	}
	return 0
}

func init() {
	proto.RegisterType((*SphericalCoordinates)(nil), "gazebo.msgs.SphericalCoordinates")
	proto.RegisterEnum("gazebo.msgs.SphericalCoordinates_SurfaceModel", SphericalCoordinates_SurfaceModel_name, SphericalCoordinates_SurfaceModel_value)
}

func init() { proto.RegisterFile("spherical_coordinates.proto", fileDescriptor105) }

var fileDescriptor105 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2e, 0xc8, 0x48,
	0x2d, 0xca, 0x4c, 0x4e, 0xcc, 0x89, 0x4f, 0xce, 0xcf, 0x2f, 0x4a, 0xc9, 0xcc, 0x4b, 0x2c, 0x49,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4f, 0xac, 0x4a, 0x4d, 0xca, 0xd7,
	0xcb, 0x2d, 0x4e, 0x2f, 0x56, 0xba, 0xcc, 0xc8, 0x25, 0x12, 0x0c, 0x53, 0xec, 0x8c, 0x50, 0x2b,
	0xe4, 0xca, 0xc5, 0x5b, 0x5c, 0x5a, 0x94, 0x96, 0x98, 0x9c, 0x1a, 0x9f, 0x9b, 0x9f, 0x92, 0x9a,
	0x23, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1, 0x67, 0xa4, 0xa7, 0x87, 0xa4, 0x5b, 0x0f, 0x9b, 0x4e, 0xbd,
	0x60, 0x88, 0x36, 0x5f, 0x90, 0x2e, 0x21, 0x11, 0x2e, 0x9e, 0x9c, 0xc4, 0x92, 0xcc, 0x92, 0xd2,
	0x94, 0xd4, 0xf8, 0x94, 0xd4, 0x74, 0x09, 0x26, 0xa0, 0x29, 0x8c, 0x42, 0xa2, 0x5c, 0xbc, 0x39,
	0xf9, 0x79, 0xe9, 0x08, 0x61, 0x66, 0xb0, 0xb0, 0x20, 0x17, 0x67, 0x6a, 0x4e, 0x6a, 0x19, 0x50,
	0x7d, 0x7e, 0x9e, 0x04, 0x0b, 0x58, 0x48, 0x98, 0x8b, 0x3b, 0x23, 0x35, 0x11, 0x68, 0x74, 0x3a,
	0x58, 0x1d, 0x2b, 0x48, 0x50, 0x49, 0x9e, 0x8b, 0x07, 0xc5, 0x12, 0x7e, 0x2e, 0x6e, 0x57, 0xc7,
	0xa0, 0x10, 0x8f, 0xf8, 0x70, 0xf7, 0x60, 0x0b, 0x13, 0x01, 0x46, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0x48, 0x5e, 0x3d, 0x00, 0x01, 0x00, 0x00,
}
